version: '3.8'

services:
  # Base de Datos Vectorial para RAG (ChromaDB)
  chromadb:
    image: chromadb/chroma:0.4.24
    container_name: local_chromadb
    ports:
      - "8000:8000"
    environment:
      - IS_PERSISTENT=TRUE
    volumes:
      - chroma_data:/chroma/chroma

volumes:
  chroma_data: