server:
  port: 8080

spring:
  application:
    name: smart-agent-backend
  ai:
    ollama:
      base-url: http://localhost:11434
      chat:
        options:
          model: phi3
      embedding:
        options:
          model: nomic-embed-text
    vectorstore:
      chroma:
        client:
          host: http://localhost
          port: 8000
        initialize-schema: true